### ISSUE TITLE
删除某个 SP 节点的 addr 和 token 配置后，日志会不停输出 “ ERROR   rpc     go-jsonrpc@v0.2.3/websocket.go:562      sending ping message: websocket: close sent”

### ISSUE THREAD

**Issue by Derek-zd** [yhio/lotus-monitor#5]
![image](https://github.com/gh-efforts/lotus-monitor/assets/54537021/e1a318e1-035a-440f-91ea-cb98843ff7fe)
![image](https://github.com/gh-efforts/lotus-monitor/assets/54537021/4d6293b7-5c80-4514-9dd5-4a3485082394)

**Comment by yhio** [comment]
9878a0982e42c70a4bbf415f2618e06c84b1c8e1 
更新了jsonrpc的版本，应该能解决，如果还是出现，导出goroutines：lotus-monitor pprof goroutines
